files:
  - source: /docs/locale/en/**/*.po
    translation: /docs/locale/%locale_with_underscore%/**/%original_file_name%
  - source: /machine-learning/docs/locale/en/**/*.po
    translation: /machine-learning/docs/locale/%locale_with_underscore%/**/%original_file_name%
  - source: /nature/docs/locale/en/**/*.po
    translation: /nature/docs/locale/%locale_with_underscore%/**/%original_file_name%
  - source: /finance/docs/locale/en/**/*.po
    translation: /finance/docs/locale/%locale_with_underscore%/**/%original_file_name%
  - source: /optimization/docs/locale/en/**/*.po
    translation: /optimization/docs/locale/%locale_with_underscore%/**/%original_file_name%
