files:
  - source: /docs/locale/en/**/*.po
    translation: /docs/locale/%locale_with_underscore%/**/%original_file_name%
  - source: /machine-learning/docs/locale/en/**/*.po
    translation: /machine-learning/docs/locale/%locale_with_underscore%/**/%original_file_name%
