name: Machine Learning Docs Publish
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - bn_BN
          - fr_FR
          - hi_IN
          - ja_JP
          - ko_KR
          - ru_RU
          - es_UN
          - ta_IN
          - tr_TR
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Qiskit machine-learning dependencies
      run: |
        cd machine-learning
        python -m pip install --upgrade pip
        pip install -U virtualenv setuptools wheel
        pip install jupyter sphinx_rtd_theme 'matplotlib<3.3.0' qiskit-terra[visualization] 'torchvision<0.10.0'
        sudo apt-get install -y pandoc graphviz
        pip install -U -r requirements-dev.txt -r requirements.txt sphinx-intl
        pip install -e .
    - name: Build translated Qiskit ML Docs
      env:
        encrypted_rclone_key: ${{ secrets.encrypted_rclone_key }}
        encrypted_rclone_iv: ${{ secrets.encrypted_rclone_iv }}
        TRANSLATION_LANG: ${{ matrix.language }}
      run: |
        cd machine-learning
        ../tools/deploy_ML_translated_documentation.sh
